apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade-feed
  template:
    metadata:
      labels:
        app: trade-feed
    spec:
      containers:
        - name: trade-feed
          image: sohelsk3/trade-feed:17
          ports:
            - containerPort: 4000
