apiVersion: apps/v1
kind: Deployment
metadata:
  name: reference-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reference-data
  template:
    metadata:
      labels:
        app: reference-data
    spec:
      containers:
        - name: reference-data
          image: sohelsk3/reference-data:latest
          ports:
            - containerPort: 3000
