apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  template:
    metadata:
      labels:
        version: green
    spec:
      containers:
        - name: account-service
          image: sohelsk3/account-service:build-28
          ports:
            - containerPort: 18088
          env:
            - name: ACCOUNT_SERVICE_PORT
              value: "18088"

