apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: traderx
spec:
  selector:
    app: account-service
    version: blue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

