apiVersion: apps/v1
kind: Deployment
metadata:
  name: people-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: people-service
  template:
    metadata:
      labels:
        app: people-service
    spec:
      containers:
        - name: people-service
          image: sohelsk3/people-service:18
          ports:
            - containerPort: 8081
