apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-service
  template:
    metadata:
      labels:
        app: position-service
    spec:
      containers:
        - name: position-service
          image: sohelsk3/position-service:latest
          ports:
            - containerPort: 8080
