apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade-service
  template:
    metadata:
      labels:
        app: trade-service
    spec:
      containers:
        - name: trade-service
          image: sohelsk3/trade-service:21
          ports:
            - containerPort: 8080
