apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - account-service-deployment.yaml
  - account-service-svc.yaml

images:
  - name: sohelsk3/account-service
    newTag: "85"

