apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustomization-reference-data
  namespace: flux-system
spec:
  interval: 1m
  path: ./reference-data
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: traderx
  timeout: 2m
